Fix/rmet 3109/serialize data objects
OutSystems/cordova-outsystems-firebase-cloud-messaging pull request #93
Opened 2024-04-17 11:30 UTC by alexgerardojacinto

## Description

## Context

## Type of changes

- [ ] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (cosmetic changes)
- [ ] Breaking change (change that would cause existing functionality to not work as expected)

## Platforms affected
- [ ] Android
- [ ] iOS
- [ ] JavaScript

## Tests

## Screenshots (if appropriate)

## Checklist

- [ ] Pull request title follows the format `RNMT-XXXX <title>`
- [ ] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

2024-04-17 11:42 UTC, OS-ricardomoreirasilva requested changes

2024-04-17 11:42 UTC, OS-ricardomoreirasilva commented on CHANGELOG.md
> +- Fix: Properly serialize data objects with annotoation (https://outsystemsrd.atlassian.net/browse/RMET-3109).
Typo: `annotation`

2024-04-17 11:47 UTC, alexgerardojacinto commented on CHANGELOG.md
> +- Fix: Properly serialize data objects with annotoation (https://outsystemsrd.atlassian.net/browse/RMET-3109).
Fixed!

2024-04-17 13:24 UTC, OS-ricardomoreirasilva approved these changes

2024-04-18 10:36 UTC, OS-martacarlos approved these changes

2024-04-18 11:14 UTC, merged